
import { Roboto } from "next/font/google";
import "./globals.css";

import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata = {
  title: "Divinitas | Trade Show Exhibits & Displays, Orlando, Florida",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="sunset">
      <body className={`${roboto.variable} antialiased flex flex-col p-1 gap-8`}>
        
          <Nav />
          {children}
        

        <Footer />
      </body>
    </html>
  );
}
